### ISSUE TITLE
No support for OTF fonts

### ISSUE THREAD

**Issue by ThiagoRangel7** [CodeZombie/TypeRip#20]
I tried to download Warnock (https://fonts.adobe.com/fonts/warnock), a font that is known for its OTF related features (ligatures, different types of the same letters etc).

All downloaded files have .ttf extension instead of .otf.

**Comment by Nickyg001** [comment]
YES! Because download ONLY TTF files?

**Comment by oghaki** [comment]
I think in Windows, OTF fonts will get the TTF extension if they have full true-type hinting, and OTF if they just have postscript outlines.  It seemed counterintuitive to me initially, but after researching, that was my understanding.  'TrueType' really refers to a complex hinting format Microsoft implemented, which, as I understand it, is still the gold standard, but a lot of foundries don't take the time with every font.  It isn't mutually exclusive with, or superseded by, OpenType.  Also, I think the OpenType container tolerates a greater variety of formats and features, kind of like a media container (e.g., MKV could contain almost any type of video or audio stream, from very old ones to the most cutting edge, and something like MP4 still tolerates a variety of streams, but official support is more narrowly constrained to make fully supporting it easier on a hardware level, or otherwise).

**Comment by CodeZombie** [comment]
TypeRip has been updated and fonts are now scraped using a new method:
1. A WOFF2 file is downloaded from adobe, which is a compressed container around either an OTF or TTF file.
2. This file is decompressed and then saved to the user's disk with a .TTF extension, even if it's an OTF file, but your font-parsing software (including the default Windows Font Installer program) should be able to make the distinction despite the "incorrect" extension.

Could you please uninstall Warnock from your system, download it with the latest version of TypeRip, and then test the font to make sure it actually contains the correct OTF features? 

I suspect it should

**Comment by ThiagoRangel7** [comment]
@CodeZombie ,
I tried it and the ligatures worked fine.

But apparently the font metadata is wrong, since I can't install the entire family, because Windows thinks that two different font files are the same. It issues the message "The font 'Warnock Pro' is already installed. Do you want to overwrite it?".

Try installing both `Warnock Pro Regular` and `Warnock Pro Italic` and you'll understand what I mean
